motha = input("mother's birth year: ")
fathu = input("father's birth year: ")
grandmotha = input("enter grandmother's birth year: ")
grandfathu = input("enter grandfather's birth year: ")
print(motha)
print(fathu)
print(grandmotha)
print(grandfathu)
input("press enter to exit the test!!! bye guizsz!!!")