import turtle
turtle.Screen().setup(420,380)
turtle.Screen().bgcolor("purple")
Pen = turtle.Turtle()
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.done()