import turtle
import time
times = int(input("how many times you wanna loop: "))
bg = input("enter the background color: ")
color = input("enter the pen color: ")
wn = input("enter page title: ")
print("installing rendering tools....")
time.sleep(3)
turtle.speed(100)
time.sleep(1)
turtle.goto(0,0)
turtle.title(wn)
turtle.Screen().bgcolor(bg)
turtle.Screen().setup(620,580)
turtle.color(color)
turtle.shapesize(1)
turtle.color = color
for i in range(times):
    turtle.forward(100)
    turtle.circle(50)
    turtle.left(10)
    turtle.forward(10)
    turtle.circle(10)
    turtle.goto(0,0)
    turtle.right(10)
    turtle.circle(10)
    turtle.left(10)
    turtle.circle(50)
turtle.done()