import tkinter
from tkinter.constants import *
tk = tkinter.Tk()
frame = tkinter.Frame(tk, relief=RIDGE, borderwidth=2)
frame.pack(fill=BOTH,expand=1)
button = tkinter.Button(frame,text="Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia",command=tk.destroy)
button = tkinter.Button(frame,text="Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia ",command=tk.destroy)
label = tkinter.Label(frame, text="")
label.pack(fill=X, expand=1)
button = tkinter.Button(frame,text="Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia Hippotomonstresesquippedelliaphobia",command=tk.destroy)
button.pack(side=BOTTOM)
tk.mainloop() 